// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crddxdieilyaqjhnsxpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZGR4ZGllaWx5YXFqaG5zeHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzM4MTcsImV4cCI6MjA2ODUwOTgxN30.H8lMyzZk-CShL42DzZ-ztI7QeNPrtdbHkLXtf1uPOoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});